module.exports = {
    country:[
        "AFGHANISTAN",
        "ALBANIA",
        "ALGERIA",
        "ANDORRA",
        "ANGOLA",
        "ANGUILIA(UNITED KINGDOM)",
        "ANTILLES(NETHERLANDS)",
        "ARGENTINA",
        "ARMENIA",
        "ARUBA(NETHERLANDS)",
        "AUSTRALIA",
        "AUSTRIA",
        "AZERBAIJAN",
        "BAHAMAS",
        "BAHRAIN",
        "BANGLADESH",
        "BARBADOS",
        "BELARUS",
        "BELGIUM",
        "BERMUDA(UNITED KINGDOM)",
        "BHUTAN",
        "BOSNIA AND HERZEGOVINA",
        "BOTSWANA",
        "BRAZIL",
        "BRUNEI DARUSSALAM",
        "BULGARIA(REP)",
        "CAMBODIA",
        "CANADA",
        "CAPE VERDE",
        "CAYMAN(UNITED KINGDOM)",
        "CENTRAL AFRICAN REP",
        "CHILE",
        "CHINA",
        "CHRISTMAS(AUSTRAILIA)",
        "COCOS(AUSTRAILIA)",
        "COLOMBIA",
        "COMOROS",
        "COOK ISLANDS(NEW ZEALAND)",
        "COSTA RICA",
        "CROATIA",
        "CUBA",
        "CYPRUS",
        "CZECH REP",
        "DEMOCRATIC REP OF THE CONGO",
        "DENMARK",
        "DJIBOUTI",
        "DOMINICAN REPUBLIC",
        "EAST TIMOR",
        "ECUADOR",
        "EGYPT",
        "EL SALVADOR",
        "EQUATORIAL GUINEA",
        "ESTONIA",
        "ETHIOPIA",
        "FAROE ISLAND(DENMARK)",
        "FIJI",
        "FINLAND",
        "FRANCE",
        "FRANCE(FRENCH SOUTHERN)",
        "FRENCH POLYNESIA(FRANCE)",
        "GABON",
        "GAMBIA",
        "GEORGIA",
        "GERMANY",
        "GHANA",
        "GIBRALTAR(UNITED KINGDOM)",
        "GREECE",
        "GREENLAND(DENMARK)",
        "GUADELOUPE(FRANCE)",
        "GUAM(U.S.A)",
        "GUATEMALA",
        "GUINEA",
        "GUINEA-BISSAU",
        "HONGKONG",
        "HUNGARY(REP) ICELAND",
        "INDIA",
        "INDONESIA",
        "IRAN(ISLAMIC REP)",
        "IRELAND",
        "ISRAEL",
        "ITALY",
        "JAPAN",
        "JORDAN",
        "KAZAKHSTAN",
        "KEDO",
        "KENYA",
        "KIRIBATI",
        "KOREA, REPUBLIC OF",
        "KUWAIT",
        "KYRGYZSTAN",
        "LAO PEOPLE'S DEM REP",
        "LATVIA",
        "LEBANON",
        "LIECHTENSTEIN",
        "LITHUANIA",
        "LUXEMBOURG",
        "MACAO(CHINA)",
        "MACEDONIA",
        "MADAGASCAR",
        "MALAWI",
        "MALAYSIA",
        "MALDIVES",
        "MALTA",
        "MARIANA ISLANDS(U.S.A)",
        "MARSHALL(U.S.A)",
        "MARTINIQUE(FRANCE)",
        "MAURITANIA",
        "MAURITIUS",
        "MAY0TTE",
        "MEXICO",
        "MICRONESIA",
        "MOLDOVA",
        "MONACO",
        "MONGOLIA",
        "MONTSERRAT(UNITED KINGDOM)",
        "MOROCCO",
        "MOZAMBIQUE",
        "MYANMAR",
        "NAMIBIA",
        "NAURU",
        "NEPAL",
        "NETHERLANDS(",
        "NEW CALEDONIA(FRANCE)",
        "NEW ZEALAND",
        "NICARAGUA",
        "NIEU(NEW ZEALAND)",
        "NIGERIA",
        "NORFOLK(AUSTRALIA)",
        "NORWAY",
        "OMAN",
        "PALAU ISLANDS(U.S.A)",
        "PANAMA(REP)",
        "PARAGUAY",
        "PERU",
        "PHILIPPINES",
        "PITCAIRN IS(UNITED KINGDUM)",
        "PUERTO RICO(U.S.A)",
        "REPUBIC OF SOUTH AFRICAN",
        "REUNION(FRANCE)",
        "RUSSIA",
        "RWANDA",
        "SAINT KITTS AND NEVIS",
        "SAINT LUCIA",
        "SAINT VINCENT AND THE GRENADIN",
        "SAMOA(U.S.A)",
        "SAO TOME AND PRINCIPE",
        "SENEGAL",
        "SEYCHELLES",
        "SINGAPORE",
        "SOLOMON ISLANDS",
        "SPAIN",
        "SRI LANKA",
        "ST PIER AND MIQUELON(FRANCE)",
        "SUDAN",
        "SURINAME",
        "SWAZILAND",
        "TAIWAN",
        "TANZANIA(UNITED REP)",
        "THAILAND",
        "TONGA(NIUAFO'OU)",
        "TRINIDAD AND TOBAGO",
        "TUNISIA",
        "TURKS(UNITED KINGDOM)",
        "TUVALU",
        "UGANDA",
        "UNITED KINGDOM",
        "UNITED STATES OF AMERICA",
        "URUGUAY",
        "VANUATU",
        "VENEZUELA",
        "VIETNAM",
        "VIRGIN(U.S.A)",
        "VIRGIN(UNITED KINGDOM)",
        "WALLIS AND FUTUNA(FRANCE)",
        "WESTERN SAMOA(U.S.A)",
        "ZAMBIA"
    ]
};